/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud.pkg2;

import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.Timer;

/**
 *
 * @author Yuzron
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        SetJam();
        setTanggal();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
   public void setTanggal() { //method untuk menampilkan tanggal
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
       txtTanggal.setText(kal.format(skrg));
   }
   
   public void SetJam(){ //method untuk jam
       ActionListener taskPerformer = new ActionListener() { //ActionListener untuk keperluan timer
        public void actionPerformed(ActionEvent evt) {
            Date dt = new Date(); //membuat Date
            int nilai_jam = dt.getHours(); //mengambil nilai jam, menit, dan detik sekarang
            int nilai_menit = dt.getMinutes(); 
            int nilai_detik = dt.getSeconds();
            String nol_jam ="";
            String nol_menit ="";
            String nol_detik ="";
            if(nilai_jam <= 9) { //jika nilai jam lebih kecil dari 10 (hanya 1 digit)
                nol_jam = "0"; //untuk menambahkan "0" didepannya
            }
            if(nilai_menit <= 9) { //jika nilai menit lebih kecil dari 10 (hanya 1 digit)
                nol_menit = "0"; //untuk menambahkan "0" didepannya
            }
            if(nilai_detik <= 9) { //jika nilai detik lebih kecil dari 10 (hanya 1 digit)
                nol_detik = "0"; //untuk menambahkan "0" didepannya
            }
            //membuat String jam , menit, dan detik
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            txtJam.setText("Jam "+jam + ":" +menit+":"+detik); //menampilkan pada label layar
        }  
}; new Timer(100, taskPerformer).start();//Timer   
   }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtJam = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jKelas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAlamat = new javax.swing.JTextArea();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTempat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTanggal = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBiodata = new javax.swing.JTable();
        bPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bedit = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        brefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 10, 450, 29);

        txtJam.setFont(new java.awt.Font("Baskerville Old Face", 1, 13)); // NOI18N
        txtJam.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtJam);
        txtJam.setBounds(530, 60, 100, 14);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("The Real Informatic School");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 70, 200, 14);

        txtTanggal.setFont(new java.awt.Font("Baskerville Old Face", 1, 13)); // NOI18N
        txtTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtTanggal);
        txtTanggal.setBounds(530, 40, 100, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 90);

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("ISIAN DATA SISWA");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 140, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 260, 30);

        jPanel3.setBackground(new java.awt.Color(102, 255, 153));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("NIS");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 20, 40, 14);
        jPanel3.add(jNis);
        jNis.setBounds(10, 40, 110, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 250, 110, 14);
        jPanel3.add(jNama);
        jNama.setBounds(10, 90, 190, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 410, 140, 14);
        jPanel3.add(jKelas);
        jKelas.setBounds(10, 330, 190, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 360, 140, 14);
        jPanel3.add(jEmail);
        jEmail.setBounds(10, 380, 190, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nama");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 70, 140, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Kelas");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 310, 140, 14);

        jAlamat.setColumns(20);
        jAlamat.setRows(5);
        jScrollPane1.setViewportView(jAlamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 440, 240, 130);

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki-Laki");
        jPanel3.add(rbLaki);
        rbLaki.setBounds(10, 280, 65, 23);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        jPanel3.add(rbPerempuan);
        rbPerempuan.setBounds(110, 280, 79, 23);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Tempat Lahir");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 130, 160, 14);
        jPanel3.add(jTempat);
        jTempat.setBounds(10, 150, 150, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Tanggal Lahir");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 180, 140, 14);
        jPanel3.add(jTanggal);
        jTanggal.setBounds(10, 210, 180, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 150, 270, 590);

        jPanel4.setBackground(new java.awt.Color(102, 255, 153));
        jPanel4.setLayout(null);

        tableBiodata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "Alamat", "TempatLahir", "TanggalLahir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBiodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBiodataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBiodata);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(20, 80, 570, 360);

        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jPanel4.add(bPrint);
        bPrint.setBounds(390, 10, 55, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(290, 170, 630, 580);

        jPanel5.setBackground(new java.awt.Color(102, 255, 153));
        jPanel5.setLayout(null);

        bedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel5.add(bedit);
        bedit.setBounds(370, 10, 80, 30);

        bsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel5.add(bsave);
        bsave.setBounds(20, 10, 80, 30);

        bdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bdelete.setText("DELETE");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel5.add(bdelete);
        bdelete.setBounds(100, 10, 90, 30);

        bclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bclear.setText("CLEAR");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel5.add(bclear);
        bclear.setBounds(190, 10, 80, 30);

        brefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brefresh.setText("REFRESH");
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });
        jPanel5.add(brefresh);
        brefresh.setBounds(270, 10, 100, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(300, 110, 630, 50);

        setSize(new java.awt.Dimension(943, 791));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        int baris = tableBiodata.getSelectedRow();
        if (baris!= -1) {
            String NIS = tableBiodata.getValueAt (baris,0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = dateFormat.format(jTanggal.getDate());
            String JK = "";
                if (rbLaki.isSelected()) {
                    JK = "L";
                } else {
                    JK="P";
                }
            if("".equals(jNis.getText()) || "".equals(jAlamat.getText()) || "".equals(jKelas.getText()) || "".equals(jNama.getText()) || "".equals(jEmail.getText()) || "".equals(jTempat.getText())|| "".equals(tanggal)) {
                JOptionPane.showMessageDialog(this, "Harap lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
                
                
             String SQL = "INSERT INTO t_siswa (NIS, NamaSiswa, JenisKelamin, Kelas, Email, Alamat, TempatLahir, TanggalLahir)"
                     + "VALUES ("+jNis.getText()+",'"+jNama.getText()+"','"+JK+"',"
                     +"'" +jKelas.getText()+"','"+jEmail.getText()+"','"+jAlamat.getText()+"','"+jTempat.getText()+"','"+tanggal+"')";
            
             int status = KoneksiDB.execute(SQL);
             if (status==1){
                 JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "SUkses", JOptionPane.INFORMATION_MESSAGE);
                 selectData();
             } else {
                 JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
                 
             }
            }
            
    }//GEN-LAST:event_bsaveActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        jNis.setText("");
        jNama.setText("");
        jKelas.setText("");
        buttonGroup1.clearSelection();
        jEmail.setText("");
        jAlamat.setText("");
        jTempat.setText("");
        
    }//GEN-LAST:event_bclearActionPerformed

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        selectData();
    }//GEN-LAST:event_brefreshActionPerformed

    public void selectData() {
            String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3))) {
                    JenisKelamin = "Laki-Laki";
                } else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
            } catch (SQLException ex) {
                
        }tableBiodata.setModel(dtm);
    
    }
    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy--MM--dd");
        String tanggal = dateFormat.format(jTanggal.getDate());
        String JK = "";
            if (rbLaki.isSelected()) {
                JK = "L";
            }else{
                JK = "P";
            }
        if (jNis.getText().equals("")||
                jNama.getText().equals("")||
                JK.equals("")||
                jTempat.getText().equals("")||                        
                tanggal.equals("")||
                jKelas.getText().equals("")||
                jEmail.getText().equals("")||
                jAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);    
        }else{
            int baris = tableBiodata.getSelectedRow();
            String nis = tableBiodata.getValueAt(baris, 0).toString();
            
            String SQL = "UPDATE t_siswa SET" 
                    +" NIS='"+jNis.getText()+"',"
                    +" NamaSiswa='"+jNama.getText()+"',"
                    +" JenisKelamin='"+JK+"',"
                    +" TempatLahir='"+jTempat.getText()+"',"
                    +" TanggalLahir='"+tanggal+"',"
                    +" Kelas='"+jKelas.getText()+"',"
                    +" Email='"+jEmail.getText()+"',"
                    +" Alamat='"+jAlamat.getText()+"' WHERE NIS="+nis;
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                 JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses", JOptionPane.INFORMATION_MESSAGE);
                 selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
            
    }//GEN-LAST:event_beditActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        MessageFormat header= new MessageFormat("Biodata Siswa SMK TELKOM Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}        ");
        try{
            tableBiodata.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrintActionPerformed

    private void tableBiodataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBiodataMouseClicked
        int baris = tableBiodata.getSelectedRow();
        if (baris != -1) {
            jNis.setText(tableBiodata.getValueAt(baris, 0).toString());
            jNama.setText(tableBiodata.getValueAt(baris, 1).toString());
        }if("Laki-Laki".equals(tableBiodata.getValueAt(baris, 2).toString())) {
            rbLaki.setSelected(true);
        }
        else{
            rbPerempuan.setSelected(true);
        }
        jKelas.setText(tableBiodata.getValueAt(baris, 3).toString());
        jEmail.setText(tableBiodata.getValueAt(baris, 4).toString());
        jAlamat.setText(tableBiodata.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_tableBiodataMouseClicked
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton bsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea jAlamat;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNama;
    private javax.swing.JTextField jNis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jTanggal;
    private javax.swing.JTextField jTempat;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tableBiodata;
    private javax.swing.JLabel txtJam;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables
}
